INSERT INTO topic (id, name) VALUES
  (1, 'Math'),
  (2, 'Science'),
  (3, 'History'),
  (4, 'Music'),
  (5, 'Sports');

INSERT INTO question (id, topic_id, question, A, B, C, D, answer) VALUES
  -- Math (IDs 1001-1050)
  (1001, 1, 'What is the only number that has the same number of letters as its value?', '3', '4', '5', '6', '4'),
  (1002, 1, 'What is the fear of numbers called?', 'Numerophobia', 'Arithmophobia', 'Mathophobia', 'Digitphobia', 'Arithmophobia'),
  (1003, 1, 'Which number is considered unlucky in Western culture?', '4', '7', '13', '17', '13'),
  (1004, 1, 'What shape has exactly 8 sides?', 'Hexagon', 'Heptagon', 'Octagon', 'Nonagon', 'Octagon'),
  (1005, 1, 'In Roman numerals, what does "L" represent?', '100', '50', '500', '1000', '50'),
  (1006, 1, 'What is the smallest prime number?', '0', '1', '2', '3', '2'),
  (1007, 1, 'What ancient civilization invented the concept of zero?', 'Greeks', 'Romans', 'Indians', 'Egyptians', 'Indians'),
  (1008, 1, 'How many sides does a dodecagon have?', '10', '11', '12', '14', '12'),
  (1009, 1, 'What is the only even prime number?', '0', '2', '4', '6', '2'),
  (1010, 1, 'What is a polygon with 1,000 sides called?', 'Megagon', 'Chiliagon', 'Kilagon', 'Millagon', 'Chiliagon'),
  (1011, 1, 'What mathematician is known as the "Father of Geometry"?', 'Pythagoras', 'Euclid', 'Archimedes', 'Plato', 'Euclid'),
  (1012, 1, 'What is 111,111,111 × 111,111,111?', '12345678987654321', '123456789987654321', '11111111111111111', '99999999999999999', '12345678987654321'),
  (1013, 1, 'Which number is both a square and triangular number (besides 1)?', '25', '36', '49', '64', '36'),
  (1014, 1, 'What is the name for a triangle with all sides equal?', 'Isosceles', 'Scalene', 'Equilateral', 'Right', 'Equilateral'),
  (1015, 1, 'In what country was algebra invented?', 'Greece', 'Persia', 'India', 'Egypt', 'Persia'),
  (1016, 1, 'What is the sum of all angles in a triangle?', '90°', '180°', '270°', '360°', '180°'),
  (1017, 1, 'What number does "googol" represent (1 followed by how many zeros)?', '10', '50', '100', '1000', '100'),
  (1018, 1, 'Which famous sequence starts 0, 1, 1, 2, 3, 5, 8...?', 'Pascal', 'Fibonacci', 'Euler', 'Bernoulli', 'Fibonacci'),
  (1019, 1, 'What is the mathematical term for a number that reads the same forwards and backwards?', 'Symmetric', 'Palindrome', 'Mirror number', 'Reversible', 'Palindrome'),
  (1020, 1, 'How many degrees are in a circle?', '180', '270', '360', '400', '360'),
  (1021, 1, 'What is the name of the longest side of a right triangle?', 'Adjacent', 'Opposite', 'Hypotenuse', 'Perpendicular', 'Hypotenuse'),
  (1022, 1, 'Who wrote "The Elements," one of the most influential math textbooks?', 'Aristotle', 'Euclid', 'Archimedes', 'Ptolemy', 'Euclid'),
  (1023, 1, 'What is the value of 0! (zero factorial)?', '0', '1', 'Undefined', 'Infinity', '1'),
  (1024, 1, 'Which number is considered unlucky in Chinese culture?', '4', '7', '13', '17', '4'),
  (1025, 1, 'What is the term for a number divisible only by 1 and itself?', 'Composite', 'Prime', 'Perfect', 'Integer', 'Prime'),
  (1026, 1, 'What do you call a 4-dimensional cube?', 'Hypercube', 'Tesseract', 'Quadracube', 'Both A and B', 'Both A and B'),
  (1027, 1, 'How many zeros are in one billion?', '6', '9', '12', '15', '9'),
  (1028, 1, 'What is the square root of 144?', '11', '12', '13', '14', '12'),
  (1029, 1, 'Which mathematician invented calculus alongside Newton?', 'Euler', 'Leibniz', 'Gauss', 'Descartes', 'Leibniz'),
  (1030, 1, 'What is the sum of the first 10 positive integers?', '45', '50', '55', '60', '55'),
  (1031, 1, 'What is the name of a number that equals the sum of its divisors?', 'Prime', 'Perfect', 'Abundant', 'Deficient', 'Perfect'),
  (1032, 1, 'The number 6 is the smallest perfect number. What is the next one?', '12', '24', '28', '36', '28'),
  (1033, 1, 'What branch of math studies shapes and their properties?', 'Algebra', 'Calculus', 'Geometry', 'Statistics', 'Geometry'),
  (1034, 1, 'In binary code, what is the decimal value of 1010?', '8', '10', '12', '20', '10'),
  (1035, 1, 'What is the highest single-digit Roman numeral?', 'V', 'X', 'IX', 'VIII', 'IX'),
  (1036, 1, 'What number multiplied by itself gives 169?', '11', '12', '13', '14', '13'),
  (1037, 1, 'What is the mathematical constant "e" approximately equal to?', '2.14', '2.72', '3.14', '3.72', '2.72'),
  (1038, 1, 'How many faces does a standard die have?', '4', '6', '8', '12', '6'),
  (1039, 1, 'What angle is formed by the hands of a clock at 3:00?', '60°', '90°', '120°', '180°', '90°'),
  (1040, 1, 'What is the cube root of 27?', '2', '3', '4', '9', '3'),
  (1041, 1, 'What is pi (π) commonly approximated as for quick calculations?', '3', '22/7', '3.14159', 'All of the above', 'All of the above'),
  (1042, 1, 'Which mathematician was famously "the last theorem" named after?', 'Euler', 'Gauss', 'Fermat', 'Riemann', 'Fermat'),
  (1043, 1, 'What is 2 to the power of 10?', '512', '1000', '1024', '2048', '1024'),
  (1044, 1, 'How many vertices does a cube have?', '4', '6', '8', '12', '8'),
  (1045, 1, 'What year did mathematicians prove Fermat''s Last Theorem?', '1985', '1994', '2001', '2010', '1994'),
  (1046, 1, 'What is the area of a circle with radius 1?', '1', 'π', '2π', 'π²', 'π'),
  (1047, 1, 'What number system uses only 0 and 1?', 'Decimal', 'Hexadecimal', 'Binary', 'Octal', 'Binary'),
  (1048, 1, 'What is the name for a quadrilateral with exactly one pair of parallel sides?', 'Parallelogram', 'Rhombus', 'Trapezoid', 'Rectangle', 'Trapezoid'),
  (1049, 1, 'How many edges does an icosahedron have?', '12', '20', '30', '60', '30'),
  (1050, 1, 'What is the factorial of 5 (5!)?', '15', '25', '120', '125', '120'),

  -- Science (IDs 2001-2050)
  (2001, 2, 'What planet is known as the Red Planet?', 'Venus', 'Mars', 'Jupiter', 'Mercury', 'Mars'),
  (2002, 2, 'How many bones are in the adult human body?', '186', '206', '226', '256', '206'),
  (2003, 2, 'What is the hardest natural substance on Earth?', 'Gold', 'Iron', 'Diamond', 'Titanium', 'Diamond'),
  (2004, 2, 'What is the largest organ in the human body?', 'Liver', 'Brain', 'Heart', 'Skin', 'Skin'),
  (2005, 2, 'What gas makes up most of Earth''s atmosphere?', 'Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen', 'Nitrogen'),
  (2006, 2, 'What is the chemical symbol for gold?', 'Au', 'Ag', 'Go', 'Gd', 'Au'),
  (2007, 2, 'How many hearts does an octopus have?', '1', '2', '3', '4', '3'),
  (2008, 2, 'What temperature is the same in Celsius and Fahrenheit?', '-40', '0', '32', '100', '-40'),
  (2009, 2, 'What is the largest planet in our solar system?', 'Saturn', 'Neptune', 'Jupiter', 'Uranus', 'Jupiter'),
  (2010, 2, 'What type of animal is a Komodo dragon?', 'Dinosaur', 'Lizard', 'Snake', 'Crocodile', 'Lizard'),
  (2011, 2, 'What is the powerhouse of the cell?', 'Nucleus', 'Ribosome', 'Mitochondria', 'Golgi body', 'Mitochondria'),
  (2012, 2, 'What is the speed of light in miles per second (approximately)?', '86,000', '186,000', '286,000', '386,000', '186,000'),
  (2013, 2, 'Which blood type is known as the universal donor?', 'A', 'B', 'AB', 'O', 'O'),
  (2014, 2, 'How long does it take light from the Sun to reach Earth?', '8 seconds', '8 minutes', '8 hours', '8 days', '8 minutes'),
  (2015, 2, 'What element has the atomic number 1?', 'Helium', 'Hydrogen', 'Oxygen', 'Carbon', 'Hydrogen'),
  (2016, 2, 'What is the most abundant element in the universe?', 'Oxygen', 'Carbon', 'Helium', 'Hydrogen', 'Hydrogen'),
  (2017, 2, 'What is the only mammal capable of true flight?', 'Flying squirrel', 'Bat', 'Sugar glider', 'Colugo', 'Bat'),
  (2018, 2, 'What planet has the most moons?', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Saturn'),
  (2019, 2, 'What is the chemical formula for table salt?', 'NaCl', 'KCl', 'CaCl2', 'MgCl2', 'NaCl'),
  (2020, 2, 'How many chromosomes do humans have?', '23', '46', '48', '64', '46'),
  (2021, 2, 'What is the hottest planet in our solar system?', 'Mercury', 'Venus', 'Mars', 'Jupiter', 'Venus'),
  (2022, 2, 'What scientist developed the theory of general relativity?', 'Newton', 'Bohr', 'Einstein', 'Hawking', 'Einstein'),
  (2023, 2, 'What is the rarest blood type?', 'A negative', 'B negative', 'AB negative', 'O negative', 'AB negative'),
  (2024, 2, 'How many teeth does an adult human typically have?', '28', '30', '32', '34', '32'),
  (2025, 2, 'What is the name of the closest star to Earth?', 'Alpha Centauri', 'Proxima Centauri', 'The Sun', 'Sirius', 'The Sun'),
  (2026, 2, 'What is the largest animal ever known to exist?', 'African elephant', 'Blue whale', 'Megalodon', 'Argentinosaurus', 'Blue whale'),
  (2027, 2, 'What noble gas is used in neon signs (besides neon)?', 'Helium', 'Argon', 'Krypton', 'All of the above', 'All of the above'),
  (2028, 2, 'What part of the brain controls balance?', 'Cerebrum', 'Cerebellum', 'Brainstem', 'Hypothalamus', 'Cerebellum'),
  (2029, 2, 'What is the only metal that is liquid at room temperature?', 'Lead', 'Aluminum', 'Mercury', 'Gallium', 'Mercury'),
  (2030, 2, 'How many taste buds does the average human have?', '2,000', '5,000', '10,000', '20,000', '10,000'),
  (2031, 2, 'What planet rotates on its side?', 'Venus', 'Mars', 'Uranus', 'Neptune', 'Uranus'),
  (2032, 2, 'What is the smallest bone in the human body?', 'Stapes', 'Incus', 'Malleus', 'Phalanx', 'Stapes'),
  (2033, 2, 'What phenomenon causes the Northern Lights?', 'Solar wind', 'Volcanic activity', 'Ocean currents', 'Meteor showers', 'Solar wind'),
  (2034, 2, 'How many muscles does it take to smile?', '12', '17', '26', '43', '17'),
  (2035, 2, 'What is the human body''s largest internal organ?', 'Heart', 'Liver', 'Lungs', 'Stomach', 'Liver'),
  (2036, 2, 'What does DNA stand for?', 'Deoxyribonucleic acid', 'Dioxyribonucleic acid', 'Deoxyribogenetic acid', 'Dinucleic acid', 'Deoxyribonucleic acid'),
  (2037, 2, 'What is the charge of an electron?', 'Positive', 'Negative', 'Neutral', 'Variable', 'Negative'),
  (2038, 2, 'How many eyes does a bee have?', '2', '3', '4', '5', '5'),
  (2039, 2, 'What gas is produced when you mix baking soda and vinegar?', 'Oxygen', 'Hydrogen', 'Carbon dioxide', 'Nitrogen', 'Carbon dioxide'),
  (2040, 2, 'What is the study of earthquakes called?', 'Geology', 'Seismology', 'Vulcanology', 'Tectonics', 'Seismology'),
  (2041, 2, 'What vitamin does the sun help your body produce?', 'Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin E', 'Vitamin D'),
  (2042, 2, 'What is the process by which plants make food called?', 'Respiration', 'Photosynthesis', 'Fermentation', 'Osmosis', 'Photosynthesis'),
  (2043, 2, 'How old is the Earth (approximately)?', '4.5 million years', '4.5 billion years', '45 billion years', '450 million years', '4.5 billion years'),
  (2044, 2, 'What is the largest desert in the world?', 'Sahara', 'Gobi', 'Antarctic', 'Arabian', 'Antarctic'),
  (2045, 2, 'What bird can fly backwards?', 'Sparrow', 'Eagle', 'Hummingbird', 'Penguin', 'Hummingbird'),
  (2046, 2, 'What is Newton''s first law also known as?', 'Law of Acceleration', 'Law of Inertia', 'Law of Gravity', 'Law of Motion', 'Law of Inertia'),
  (2047, 2, 'What color does litmus paper turn in acid?', 'Blue', 'Red', 'Green', 'Yellow', 'Red'),
  (2048, 2, 'How many legs does a spider have?', '6', '8', '10', '12', '8'),
  (2049, 2, 'What is the name of the scale used to measure earthquake intensity?', 'Fujita', 'Richter', 'Beaufort', 'Saffir-Simpson', 'Richter'),
  (2050, 2, 'What percentage of the human body is water?', '40%', '50%', '60%', '70%', '60%'),

  -- History (IDs 3001-3050)
  (3001, 3, 'In what year did the Titanic sink?', '1910', '1912', '1914', '1916', '1912'),
  (3002, 3, 'Who was the first woman to fly solo across the Atlantic?', 'Bessie Coleman', 'Amelia Earhart', 'Harriet Quimby', 'Jacqueline Cochran', 'Amelia Earhart'),
  (3003, 3, 'What was the name of the first successful English colony in America?', 'Plymouth', 'Roanoke', 'Jamestown', 'Massachusetts Bay', 'Jamestown'),
  (3004, 3, 'Which ancient wonder was located in Alexandria?', 'Colossus', 'Lighthouse', 'Hanging Gardens', 'Temple of Artemis', 'Lighthouse'),
  (3005, 3, 'What year did the Berlin Wall fall?', '1987', '1989', '1991', '1993', '1989'),
  (3006, 3, 'Who painted the Mona Lisa?', 'Michelangelo', 'Raphael', 'Leonardo da Vinci', 'Donatello', 'Leonardo da Vinci'),
  (3007, 3, 'What empire was ruled by Genghis Khan?', 'Persian', 'Ottoman', 'Mongol', 'Roman', 'Mongol'),
  (3008, 3, 'In which city was John F. Kennedy assassinated?', 'Washington D.C.', 'Dallas', 'Los Angeles', 'Chicago', 'Dallas'),
  (3009, 3, 'What was the first country to give women the right to vote?', 'United States', 'United Kingdom', 'New Zealand', 'Australia', 'New Zealand'),
  (3010, 3, 'Who was the youngest president of the United States?', 'John F. Kennedy', 'Theodore Roosevelt', 'Bill Clinton', 'Barack Obama', 'Theodore Roosevelt'),
  (3011, 3, 'What ship brought the Pilgrims to America?', 'Santa Maria', 'Mayflower', 'Endeavour', 'Victory', 'Mayflower'),
  (3012, 3, 'In what year did man first walk on the moon?', '1967', '1968', '1969', '1970', '1969'),
  (3013, 3, 'Who was the first Emperor of Rome?', 'Julius Caesar', 'Augustus', 'Nero', 'Caligula', 'Augustus'),
  (3014, 3, 'What ancient city was buried by Mount Vesuvius?', 'Rome', 'Athens', 'Pompeii', 'Naples', 'Pompeii'),
  (3015, 3, 'Which queen of England ruled for 63 years until 1901?', 'Elizabeth I', 'Victoria', 'Mary', 'Anne', 'Victoria'),
  (3016, 3, 'What war was fought between 1914 and 1918?', 'Civil War', 'World War I', 'World War II', 'Korean War', 'World War I'),
  (3017, 3, 'Who discovered penicillin?', 'Louis Pasteur', 'Joseph Lister', 'Alexander Fleming', 'Robert Koch', 'Alexander Fleming'),
  (3018, 3, 'What was the name of Henry VIII''s first wife?', 'Anne Boleyn', 'Catherine of Aragon', 'Jane Seymour', 'Catherine Howard', 'Catherine of Aragon'),
  (3019, 3, 'In which century did the Black Death devastate Europe?', '12th', '13th', '14th', '15th', '14th'),
  (3020, 3, 'Who invented the telephone?', 'Thomas Edison', 'Nikola Tesla', 'Alexander Graham Bell', 'Guglielmo Marconi', 'Alexander Graham Bell'),
  (3021, 3, 'What treaty ended World War I?', 'Treaty of Paris', 'Treaty of Versailles', 'Treaty of Ghent', 'Treaty of Vienna', 'Treaty of Versailles'),
  (3022, 3, 'Who was the Egyptian queen known for her relationship with Julius Caesar?', 'Nefertiti', 'Hatshepsut', 'Cleopatra', 'Nefertari', 'Cleopatra'),
  (3023, 3, 'What was the last state to join the USA?', 'Alaska', 'Hawaii', 'Arizona', 'New Mexico', 'Hawaii'),
  (3024, 3, 'Who wrote the Communist Manifesto with Friedrich Engels?', 'Lenin', 'Stalin', 'Marx', 'Trotsky', 'Marx'),
  (3025, 3, 'What famous document begins with "We the People"?', 'Declaration of Independence', 'Bill of Rights', 'US Constitution', 'Magna Carta', 'US Constitution'),
  (3026, 3, 'In what country did the Renaissance begin?', 'France', 'Spain', 'Italy', 'Germany', 'Italy'),
  (3027, 3, 'Who was the British Prime Minister during most of World War II?', 'Neville Chamberlain', 'Winston Churchill', 'Clement Attlee', 'Anthony Eden', 'Winston Churchill'),
  (3028, 3, 'What year did the Great Fire of London occur?', '1566', '1666', '1766', '1866', '1666'),
  (3029, 3, 'Which civilization built Machu Picchu?', 'Aztec', 'Maya', 'Inca', 'Olmec', 'Inca'),
  (3030, 3, 'Who was the first person to circumnavigate the globe?', 'Christopher Columbus', 'Ferdinand Magellan', 'Juan Sebastián Elcano', 'Vasco da Gama', 'Juan Sebastián Elcano'),
  (3031, 3, 'What year did the French Revolution begin?', '1776', '1789', '1799', '1804', '1789'),
  (3032, 3, 'Who assassinated Abraham Lincoln?', 'Lee Harvey Oswald', 'John Wilkes Booth', 'Charles Guiteau', 'Leon Czolgosz', 'John Wilkes Booth'),
  (3033, 3, 'What was the name of the first permanent English settlement in India?', 'Bombay', 'Calcutta', 'Madras', 'Surat', 'Surat'),
  (3034, 3, 'In what year did the American Civil War end?', '1863', '1864', '1865', '1866', '1865'),
  (3035, 3, 'Who was known as the Sun King of France?', 'Louis XIII', 'Louis XIV', 'Louis XV', 'Louis XVI', 'Louis XIV'),
  (3036, 3, 'What empire was founded by Cyrus the Great?', 'Babylonian', 'Assyrian', 'Persian', 'Median', 'Persian'),
  (3037, 3, 'In which war was the Battle of Gettysburg fought?', 'Revolutionary War', 'War of 1812', 'Civil War', 'World War I', 'Civil War'),
  (3038, 3, 'Who was the first human to travel to space?', 'Neil Armstrong', 'Yuri Gagarin', 'John Glenn', 'Alan Shepard', 'Yuri Gagarin'),
  (3039, 3, 'What year was the Declaration of Independence signed?', '1774', '1775', '1776', '1777', '1776'),
  (3040, 3, 'Who led the Soviet Union during the Cuban Missile Crisis?', 'Stalin', 'Khrushchev', 'Brezhnev', 'Gorbachev', 'Khrushchev'),
  (3041, 3, 'What was the code name for the D-Day invasion?', 'Operation Overlord', 'Operation Barbarossa', 'Operation Sea Lion', 'Operation Torch', 'Operation Overlord'),
  (3042, 3, 'Which Greek philosopher was the teacher of Alexander the Great?', 'Socrates', 'Plato', 'Aristotle', 'Pythagoras', 'Aristotle'),
  (3043, 3, 'What year did the Boston Tea Party occur?', '1770', '1773', '1775', '1776', '1773'),
  (3044, 3, 'Who was the first female Prime Minister of the United Kingdom?', 'Margaret Thatcher', 'Theresa May', 'Queen Victoria', 'Elizabeth I', 'Margaret Thatcher'),
  (3045, 3, 'What empire built the Great Wall of China?', 'Ming Dynasty', 'Qin Dynasty', 'Han Dynasty', 'Tang Dynasty', 'Qin Dynasty'),
  (3046, 3, 'In what year did the stock market crash leading to the Great Depression?', '1927', '1928', '1929', '1930', '1929'),
  (3047, 3, 'Who was the Norse god of thunder?', 'Odin', 'Thor', 'Loki', 'Freya', 'Thor'),
  (3048, 3, 'What city was the capital of the Byzantine Empire?', 'Rome', 'Athens', 'Constantinople', 'Alexandria', 'Constantinople'),
  (3049, 3, 'Who invented the printing press?', 'Johannes Gutenberg', 'Benjamin Franklin', 'William Caxton', 'Aldus Manutius', 'Johannes Gutenberg'),
  (3050, 3, 'What was the last dynasty to rule China?', 'Ming', 'Qing', 'Tang', 'Han', 'Qing'),

  -- Music (IDs 4001-4050)
  (4001, 4, 'What band was Freddie Mercury the lead singer of?', 'The Beatles', 'Led Zeppelin', 'Queen', 'Pink Floyd', 'Queen'),
  (4002, 4, 'What instrument has 88 keys?', 'Organ', 'Harpsichord', 'Piano', 'Accordion', 'Piano'),
  (4003, 4, 'Which classical composer was deaf?', 'Mozart', 'Beethoven', 'Bach', 'Haydn', 'Beethoven'),
  (4004, 4, 'What is the real name of the artist known as Lady Gaga?', 'Stefani Germanotta', 'Elizabeth Grant', 'Robyn Fenty', 'Alecia Moore', 'Stefani Germanotta'),
  (4005, 4, 'What country is ABBA from?', 'Norway', 'Denmark', 'Sweden', 'Finland', 'Sweden'),
  (4006, 4, 'What is the best-selling album of all time?', 'Abbey Road', 'Thriller', 'Back in Black', 'The Dark Side of the Moon', 'Thriller'),
  (4007, 4, 'How many strings does a standard guitar have?', '4', '5', '6', '8', '6'),
  (4008, 4, 'What instrument does a percussionist typically NOT play?', 'Drums', 'Xylophone', 'Cello', 'Cymbals', 'Cello'),
  (4009, 4, 'What decade did MTV first air?', '1970s', '1980s', '1990s', '2000s', '1980s'),
  (4010, 4, 'Which Beatle was assassinated in 1980?', 'Paul McCartney', 'John Lennon', 'Ringo Starr', 'George Harrison', 'John Lennon'),
  (4011, 4, 'What is the musical term for playing loudly?', 'Piano', 'Forte', 'Mezzo', 'Adagio', 'Forte'),
  (4012, 4, 'What artist is known as the "King of Pop"?', 'Elvis Presley', 'Prince', 'Michael Jackson', 'James Brown', 'Michael Jackson'),
  (4013, 4, 'What instrument family does the saxophone belong to?', 'Brass', 'String', 'Woodwind', 'Percussion', 'Woodwind'),
  (4014, 4, 'Which rock band released "Stairway to Heaven"?', 'The Who', 'Led Zeppelin', 'Pink Floyd', 'Deep Purple', 'Led Zeppelin'),
  (4015, 4, 'What country did reggae music originate from?', 'Cuba', 'Jamaica', 'Brazil', 'Trinidad', 'Jamaica'),
  (4016, 4, 'What is the national anthem of the United States called?', 'America the Beautiful', 'God Bless America', 'The Star-Spangled Banner', 'My Country Tis of Thee', 'The Star-Spangled Banner'),
  (4017, 4, 'How many members were in the Spice Girls?', '4', '5', '6', '7', '5'),
  (4018, 4, 'Which composer wrote "The Four Seasons"?', 'Bach', 'Mozart', 'Vivaldi', 'Handel', 'Vivaldi'),
  (4019, 4, 'What band sang "Bohemian Rhapsody"?', 'The Who', 'Led Zeppelin', 'Queen', 'The Rolling Stones', 'Queen'),
  (4020, 4, 'What music genre did Elvis Presley help popularize?', 'Jazz', 'Rock and Roll', 'Country', 'Blues', 'Rock and Roll'),
  (4021, 4, 'What is Rihanna''s home country?', 'Jamaica', 'Barbados', 'Trinidad', 'Bahamas', 'Barbados'),
  (4022, 4, 'What instrument is Yo-Yo Ma famous for playing?', 'Violin', 'Viola', 'Cello', 'Double bass', 'Cello'),
  (4023, 4, 'What rock band has the iconic "tongue and lips" logo?', 'Aerosmith', 'Kiss', 'The Rolling Stones', 'AC/DC', 'The Rolling Stones'),
  (4024, 4, 'Which singer is known as "The Material Girl"?', 'Cyndi Lauper', 'Madonna', 'Whitney Houston', 'Janet Jackson', 'Madonna'),
  (4025, 4, 'What musical features the song "Defying Gravity"?', 'Phantom of the Opera', 'Les Misérables', 'Wicked', 'Hamilton', 'Wicked'),
  (4026, 4, 'What is the lowest male singing voice called?', 'Tenor', 'Baritone', 'Bass', 'Alto', 'Bass'),
  (4027, 4, 'Which British band had members including Mick Jagger and Keith Richards?', 'The Beatles', 'The Who', 'Led Zeppelin', 'The Rolling Stones', 'The Rolling Stones'),
  (4028, 4, 'What year did Woodstock festival take place?', '1967', '1968', '1969', '1970', '1969'),
  (4029, 4, 'What singer was known as the "Queen of Soul"?', 'Whitney Houston', 'Aretha Franklin', 'Diana Ross', 'Gladys Knight', 'Aretha Franklin'),
  (4030, 4, 'How many symphonies did Beethoven compose?', '5', '7', '9', '12', '9'),
  (4031, 4, 'What instrument is used to tune an orchestra?', 'Violin', 'Oboe', 'Flute', 'Clarinet', 'Oboe'),
  (4032, 4, 'What K-pop group performed at the 2022 Grammy Awards?', 'BLACKPINK', 'BTS', 'EXO', 'Twice', 'BTS'),
  (4033, 4, 'What is the name of the famous opera house in Sydney, Australia?', 'Royal Opera House', 'Sydney Opera House', 'La Scala', 'Metropolitan Opera', 'Sydney Opera House'),
  (4034, 4, 'What was Elvis Presley''s nickname?', 'The Boss', 'The King', 'The Duke', 'The Prince', 'The King'),
  (4035, 4, 'Which rapper''s real name is Marshall Mathers?', 'Jay-Z', 'Eminem', 'Kanye West', 'Snoop Dogg', 'Eminem'),
  (4036, 4, 'What is the term for a song with no instrumental accompaniment?', 'Solo', 'A cappella', 'Acoustic', 'Unplugged', 'A cappella'),
  (4037, 4, 'Which musical was inspired by the life of Alexander Hamilton?', 'Les Misérables', '1776', 'Hamilton', 'Founding Fathers', 'Hamilton'),
  (4038, 4, 'What does "MTV" stand for?', 'Music Television', 'Musical Theatre Venue', 'Media and TV', 'Modern Television', 'Music Television'),
  (4039, 4, 'What artist released the album "1989"?', 'Katy Perry', 'Adele', 'Taylor Swift', 'Beyoncé', 'Taylor Swift'),
  (4040, 4, 'Which composer wrote "The Magic Flute"?', 'Beethoven', 'Mozart', 'Wagner', 'Verdi', 'Mozart'),
  (4041, 4, 'What is the highest female singing voice called?', 'Alto', 'Mezzo-soprano', 'Soprano', 'Contralto', 'Soprano'),
  (4042, 4, 'Which band performed the song "Hotel California"?', 'The Eagles', 'Fleetwood Mac', 'The Doobie Brothers', 'Lynyrd Skynyrd', 'The Eagles'),
  (4043, 4, 'What is the name of the lead singer of U2?', 'Bono', 'Sting', 'Edge', 'Adam', 'Bono'),
  (4044, 4, 'How many keys are typically on a standard grand piano?', '76', '84', '88', '92', '88'),
  (4045, 4, 'Which pop star is known as "Slim Shady"?', 'Dr. Dre', 'Eminem', '50 Cent', 'Ice Cube', 'Eminem'),
  (4046, 4, 'What dance music genre originated in Detroit in the 1980s?', 'House', 'Techno', 'Disco', 'Trance', 'Techno'),
  (4047, 4, 'Which Irish rock band released "With or Without You"?', 'U2', 'The Cranberries', 'Thin Lizzy', 'Snow Patrol', 'U2'),
  (4048, 4, 'What instrument is featured prominently in jazz music?', 'Violin', 'Saxophone', 'Tuba', 'Harp', 'Saxophone'),
  (4049, 4, 'What British singer is known for the song "Someone Like You"?', 'Amy Winehouse', 'Adele', 'Dua Lipa', 'Jessie J', 'Adele'),
  (4050, 4, 'In music notation, how many lines are in a staff?', '4', '5', '6', '7', '5'),

  -- Sports (IDs 5001-5050)
  (5001, 5, 'How many players are on a basketball team on the court?', '4', '5', '6', '7', '5'),
  (5002, 5, 'In what sport would you perform a slam dunk?', 'Volleyball', 'Basketball', 'Tennis', 'Football', 'Basketball'),
  (5003, 5, 'What country won the first FIFA World Cup in 1930?', 'Brazil', 'Argentina', 'Uruguay', 'Italy', 'Uruguay'),
  (5004, 5, 'How many holes are played in a standard round of golf?', '9', '12', '18', '21', '18'),
  (5005, 5, 'What sport is played at Wimbledon?', 'Golf', 'Cricket', 'Tennis', 'Rugby', 'Tennis'),
  (5006, 5, 'How many points is a 3-point shot worth in basketball?', '2', '3', '4', '5', '3'),
  (5007, 5, 'What is the national sport of Canada?', 'Hockey', 'Lacrosse', 'Curling', 'Both A and B', 'Both A and B'),
  (5008, 5, 'How long is an Olympic swimming pool in meters?', '25', '50', '75', '100', '50'),
  (5009, 5, 'What color is the center of an archery target?', 'Red', 'Blue', 'Yellow/Gold', 'White', 'Yellow/Gold'),
  (5010, 5, 'In which sport might you throw a "curveball"?', 'Football', 'Baseball', 'Basketball', 'Soccer', 'Baseball'),
  (5011, 5, 'How many rings are on the Olympic flag?', '4', '5', '6', '7', '5'),
  (5012, 5, 'What tennis player has won the most Grand Slam titles (men)?', 'Roger Federer', 'Rafael Nadal', 'Novak Djokovic', 'Pete Sampras', 'Novak Djokovic'),
  (5013, 5, 'What sport uses a puck?', 'Hockey', 'Lacrosse', 'Curling', 'Field Hockey', 'Hockey'),
  (5014, 5, 'How many players are on a soccer team on the field?', '9', '10', '11', '12', '11'),
  (5015, 5, 'What country has won the most FIFA World Cup titles?', 'Germany', 'Argentina', 'Italy', 'Brazil', 'Brazil'),
  (5016, 5, 'In American football, how many points is a field goal worth?', '1', '2', '3', '6', '3'),
  (5017, 5, 'What is the term for three strikes in a row in bowling?', 'Triple', 'Turkey', 'Hat trick', 'Trifecta', 'Turkey'),
  (5018, 5, 'What martial art became an Olympic sport in 2000?', 'Karate', 'Judo', 'Taekwondo', 'Kung Fu', 'Taekwondo'),
  (5019, 5, 'How many dimples does an average golf ball have?', '136', '236', '336', '436', '336'),
  (5020, 5, 'What is the only country to have played in every FIFA World Cup?', 'Germany', 'Italy', 'Brazil', 'Argentina', 'Brazil'),
  (5021, 5, 'In what city were the first modern Olympics held?', 'Paris', 'London', 'Athens', 'Rome', 'Athens'),
  (5022, 5, 'What is the maximum score possible in a single frame of bowling?', '10', '12', '20', '30', '30'),
  (5023, 5, 'What sport does Tiger Woods play?', 'Tennis', 'Golf', 'Basketball', 'Baseball', 'Golf'),
  (5024, 5, 'How many innings are in a regulation Major League Baseball game?', '7', '8', '9', '10', '9'),
  (5025, 5, 'What is the diameter of a basketball hoop in inches?', '14', '16', '18', '20', '18'),
  (5026, 5, 'What country is the Tour de France held in?', 'Spain', 'Italy', 'France', 'Belgium', 'France'),
  (5027, 5, 'In boxing, what is a TKO?', 'Technical Knockout', 'Total Knockout', 'Time Knockout', 'Tactical Knockout', 'Technical Knockout'),
  (5028, 5, 'Which NFL team has won the most Super Bowls?', 'Dallas Cowboys', 'New England Patriots', 'Pittsburgh Steelers', 'San Francisco 49ers', 'New England Patriots'),
  (5029, 5, 'How many feathers are on a regulation badminton shuttlecock?', '12', '14', '16', '18', '16'),
  (5030, 5, 'What sport is known as "the beautiful game"?', 'Tennis', 'Soccer', 'Basketball', 'Baseball', 'Soccer'),
  (5031, 5, 'What is the oldest tennis tournament in the world?', 'US Open', 'French Open', 'Australian Open', 'Wimbledon', 'Wimbledon'),
  (5032, 5, 'In what year did Michael Jordan retire for the final time?', '1998', '1999', '2001', '2003', '2003'),
  (5033, 5, 'How many periods are in an NHL hockey game?', '2', '3', '4', '5', '3'),
  (5034, 5, 'What country invented baseball?', 'United States', 'England', 'Cuba', 'Japan', 'United States'),
  (5035, 5, 'What is the highest possible break in snooker?', '147', '155', '167', '180', '147'),
  (5036, 5, 'How many players are on a volleyball team on the court?', '4', '5', '6', '7', '6'),
  (5037, 5, 'What boxer was known as "The Greatest"?', 'Mike Tyson', 'Muhammad Ali', 'Joe Frazier', 'George Foreman', 'Muhammad Ali'),
  (5038, 5, 'What city hosted the 2016 Summer Olympics?', 'London', 'Beijing', 'Rio de Janeiro', 'Tokyo', 'Rio de Janeiro'),
  (5039, 5, 'In tennis, what is the score of zero called?', 'Nil', 'Zero', 'Love', 'Nothing', 'Love'),
  (5040, 5, 'What is the weight of an official NBA basketball in ounces?', '18', '20', '22', '24', '22'),
  (5041, 5, 'What sport uses the terms "spare" and "strike"?', 'Golf', 'Bowling', 'Darts', 'Archery', 'Bowling'),
  (5042, 5, 'Which country has won the most Olympic gold medals overall?', 'China', 'Russia', 'United States', 'Great Britain', 'United States'),
  (5043, 5, 'What is the distance of a marathon in miles (approximately)?', '20', '24', '26', '30', '26'),
  (5044, 5, 'In which sport can you win the Stanley Cup?', 'Basketball', 'Hockey', 'Baseball', 'Football', 'Hockey'),
  (5045, 5, 'What country did Pelé play soccer for?', 'Argentina', 'Brazil', 'Portugal', 'Spain', 'Brazil'),
  (5046, 5, 'How many points is a touchdown worth in American football?', '3', '4', '6', '7', '6'),
  (5047, 5, 'What is the name of the championship game in American football?', 'World Series', 'Super Bowl', 'Finals', 'Championship Cup', 'Super Bowl'),
  (5048, 5, 'How many bases are there in baseball?', '3', '4', '5', '6', '4'),
  (5049, 5, 'What color belt is the highest rank in most martial arts?', 'Red', 'Black', 'White', 'Brown', 'Black'),
  (5050, 5, 'In which sport would you perform a "hat trick"?', 'Golf', 'Tennis', 'Soccer/Hockey', 'Basketball', 'Soccer/Hockey');