INSERT INTO topic (id, name) VALUES
  (1, 'Math'),
  (2, 'Science'),
  (3, 'History'),
  (4, 'Music'),
  (5, 'Sports');

INSERT INTO question (id, topic_id, question, A, B, C, D, answer) VALUES
  -- Math (IDs 1001-1010)
  (1001, 1, 'What is 2 + 2?', '1', '3', '4', '5', '4'),
  (1002, 1, 'What is the square root of 81?', '7', '8', '9', '10', '9'),
  (1003, 1, 'Solve: 5 × 6', '11', '25', '30', '36', '30'),
  (1004, 1, 'What is 12 ÷ 3?', '2', '3', '4', '6', '4'),
  (1005, 1, 'What is 9 + 7?', '14', '15', '16', '17', '16'),
  (1006, 1, 'Which number is prime?', '21', '29', '33', '35', '29'),
  (1007, 1, 'What is 3²?', '3', '6', '9', '12', '9'),
  (1008, 1, 'What is 15% of 100?', '10', '12', '15', '20', '15'),
  (1009, 1, 'What is 0.5 expressed as a fraction?', '1/2', '1/3', '2/5', '3/5', '1/2'),
  (1010, 1, 'What is the value of π (pi) rounded to two decimals?', '3.00', '3.14', '3.24', '3.41', '3.14'),
  -- Science (IDs 2001-2010)
  (2001, 2, 'What planet is known as the Red Planet?', 'Venus', 'Mars', 'Jupiter', 'Mercury', 'Mars'),
  (2002, 2, 'Water boils at what temperature in Celsius?', '50°C', '75°C', '100°C', '150°C', '100°C'),
  (2003, 2, 'What gas do plants breathe in?', 'Oxygen', 'Carbon dioxide', 'Nitrogen', 'Helium', 'Carbon dioxide'),
  (2004, 2, 'What part of the cell contains DNA?', 'Cytoplasm', 'Nucleus', 'Cell wall', 'Golgi body', 'Nucleus'),
  (2005, 2, 'What force keeps us on the ground?', 'Friction', 'Electricity', 'Gravity', 'Magnetism', 'Gravity'),
  (2006, 2, 'What is the chemical symbol for gold?', 'Au', 'Ag', 'Go', 'Gd', 'Au'),
  (2007, 2, 'Which organ pumps blood?', 'Lungs', 'Brain', 'Heart', 'Liver', 'Heart'),
  (2008, 2, 'How many planets are in our solar system?', '7', '8', '9', '10', '8'),
  (2009, 2, 'What do bees collect from flowers?', 'Seeds', 'Nectar', 'Water', 'Sand', 'Nectar'),
  (2010, 2, 'What gas do humans need to survive?', 'Helium', 'Hydrogen', 'Oxygen', 'Carbon dioxide', 'Oxygen'),
  -- History (IDs 3001-3010)
  (3001, 3, 'Who wrote the Declaration of Independence?', 'George Washington', 'Thomas Jefferson', 'John Adams', 'Benjamin Franklin', 'Thomas Jefferson'),
  (3002, 3, 'In which year did World War II end?', '1943', '1945', '1948', '1950', '1945'),
  (3003, 3, 'Who was the first President of the United States?', 'George Washington', 'John Adams', 'Thomas Jefferson', 'James Madison', 'George Washington'),
  (3004, 3, 'Which empire built the Colosseum?', 'Greek', 'Roman', 'Persian', 'Ottoman', 'Roman'),
  (3005, 3, 'Who discovered America in 1492?', 'Marco Polo', 'Christopher Columbus', 'Ferdinand Magellan', 'Vasco da Gama', 'Christopher Columbus'),
  (3006, 3, 'The Magna Carta was signed in which country?', 'France', 'England', 'Spain', 'Germany', 'England'),
  (3007, 3, 'Who led India to independence using nonviolence?', 'Subhas Chandra Bose', 'Jawaharlal Nehru', 'Mahatma Gandhi', 'B. R. Ambedkar', 'Mahatma Gandhi'),
  (3008, 3, 'Which war was fought between the North and South regions in the U.S.?', 'World War I', 'American Civil War', 'Revolutionary War', 'Vietnam War', 'American Civil War'),
  (3009, 3, 'Who was known as the Maid of Orléans?', 'Queen Elizabeth I', 'Cleopatra', 'Joan of Arc', 'Catherine the Great', 'Joan of Arc'),
  (3010, 3, 'Where were the ancient pyramids built?', 'Greece', 'Egypt', 'Mexico', 'China', 'Egypt'),
  -- Music (IDs 4001-4010)
  (4001, 4, 'Which clef is typically used for violin music?', 'Bass', 'Treble', 'Alto', 'Tenor', 'Treble'),
  (4002, 4, 'How many notes are in a standard major scale?', '5', '6', '7', '8', '7'),
  (4003, 4, 'Which instrument has 88 keys?', 'Violin', 'Flute', 'Piano', 'Trumpet', 'Piano'),
  (4004, 4, 'Who composed the Fifth Symphony?', 'Mozart', 'Beethoven', 'Bach', 'Haydn', 'Beethoven'),
  (4005, 4, 'What do we call a person who writes music?', 'Conductor', 'Composer', 'Soloist', 'Lyricist', 'Composer'),
  (4006, 4, 'What is the musical term for “soft”?', 'Forte', 'Piano', 'Allegro', 'Crescendo', 'Piano'),
  (4007, 4, 'Which family does the trumpet belong to?', 'String', 'Woodwind', 'Brass', 'Percussion', 'Brass'),
  (4008, 4, 'Which note is a whole step above C?', 'C#', 'D', 'E', 'F', 'D'),
  (4009, 4, 'What does a sharp sign do to a note?', 'Lowers it', 'Raises it', 'Silences it', 'Doubles it', 'Raises it'),
  (4010, 4, 'Which Italian word means “very fast”?', 'Adagio', 'Andante', 'Presto', 'Grave', 'Presto'),
  -- Sports (IDs 5001-5010)
  (5001, 5, 'How many players are on a baseball field for one team?', '7', '8', '9', '10', '9'),
  (5002, 5, 'How many points is a touchdown worth?', '3', '6', '7', '8', '6'),
  (5003, 5, 'In basketball, how many points is a free throw worth?', '1', '2', '3', '4', '1'),
  (5004, 5, 'Which sport uses a shuttlecock?', 'Tennis', 'Badminton', 'Squash', 'Rugby', 'Badminton'),
  (5005, 5, 'How many rings are on the Olympic flag?', '3', '4', '5', '6', '5'),
  (5006, 5, 'What sport is known as “the beautiful game”?', 'Baseball', 'Cricket', 'Soccer', 'Hockey', 'Soccer'),
  (5007, 5, 'In golf, what is one stroke under par called?', 'Bogey', 'Birdie', 'Eagle', 'Par', 'Birdie'),
  (5008, 5, 'Which sport features the Stanley Cup?', 'Baseball', 'Basketball', 'Hockey', 'Soccer', 'Hockey'),
  (5009, 5, 'How many innings are in a standard baseball game?', '7', '8', '9', '12', '9'),
  (5010, 5, 'What color card sends a soccer player off?', 'Blue', 'Yellow', 'Green', 'Red', 'Red');

